{
  "crud": {
    "allowed_actions": [
      "indices:data/write/bulk",
      "indices:data/write/index",
      "indices:data/write/delete"
    ]
  },
  "read": {
    "allowed_actions": [
      "indices:data/read/search",
      "indices:data/read/get"
    ]
  },
  "admin": {
    "allowed_actions": [
      "*"
    ]
  }
}
