{
  "admin": {
    "backend_roles": ["admin"],
    "users": ["*"],
    "admin_roles": ["admin"]
  },
  "employee-reader": {
    "backend_roles": ["employee-reader"],
    "users": ["*"],
    "index_permissions": [
      {
        "index_patterns": ["employees"],
        "allowed_actions": [
          "indices:data/read/search",
          "indices:data/read/get"
        ]
      }
    ]
  },
  "employee-writer": {
    "backend_roles": ["employee-writer"],
    "users": ["*"],
    "index_permissions": [
      {
        "index_patterns": ["employees"],
        "allowed_actions": [
          "indices:data/write/index",
          "indices:data/write/bulk",
          "indices:data/write/delete"
        ]
      }
    ]
  }
}
